### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by jsgounot** [SeanChenHCY/metaLAS#1]
Hi,

I tried to run your pipeline without success. Using only conda, I'm unable to build the environment (Ubuntu 18.04, python 3.9):

```
CreateCondaEnvironmentException:
Could not create conda environment from /mnt/volume1/analyses/metaLAS/metaLAS/envs/megahit.yml:
Encountered problems while solving.
Problem: nothing provides __glibc >=2.17 needed by libgcc-ng-9.3.0-h5101ec6_17
Problem: nothing provides __glibc >=2.17 needed by libstdcxx-ng-9.3.0-hd4cf53a_17
Problem: nothing provides __glibc >=2.17 needed by libgcc-ng-9.3.0-h5101ec6_17
```

I tried to switch to Singularity and apparently container is unable to locate my files:

```
snakemake -s metaLAS --configfile config.yaml --cores 2 --use-singularity --use-conda --singularity-args '--bind /'
```

I used only 2 cores for a test run.

```
Activating singularity image /mnt/volume1/analyses/metaLAS/metaLAS/.snakemake/singularity/338a25c13dfa4d0cc393f05dd4dbf75e.simg
Activating conda environment: /conda-envs/df2364ba32d10ac40aa5b7d3d541d8e7
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
[2021-08-30 07:27:26] INFO: Starting Flye 2.8.1-b1676
[2021-08-30 07:27:26] ERROR: Can't open /mnt/volume1/subdata/ISR/TLL01/Nanopore/N254_barcode01.fastq.gz
[2021-08-30 07:27:26] ERROR: Pipeline aborted
```

I never used Singularity before so maybe this is a stupid error on my side?

**Comment by jsgounot** [comment]
Edit: I've been able to fix the Singularity issue, it's just that it does not like symbolic links.

**Comment by SeanChenHCY** [comment]
I think '--bind /mnt' will work. 

If possible, please let me know if the workflow can be run successfully on your system or not.  Thanks!

**Comment by jsgounot** [comment]
Hi,

the pipeline finally finished and worked almost perfectly. The unique line I needed to modify was an internal call for a mapping ([here](https://github.com/SeanChenHCY/metaLAS/blob/854db6a966a11ab628ad33fa3264a74cfc54eef9/scripts/pilon_polish.py#L48)) where 8Gb of memory are given _per thread_ which is kinda insane. Overall, the memory does not look like well managed (I saw at one point that 150G of memory is given to Pilon), not every one works in big clusters. 

I have additional questions and remarks but this is not directly linked to the issue.
Would you accept to talk via mail?

Regards,
JS

**Comment by SeanChenHCY** [comment]
Sure! Here is my email address:s871818@gmail.com
